# Generated by Django 3.1.3 on 2020-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('img_url', models.CharField(max_length=1200)),
                ('story', models.TextField()),
                ('people', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('genre', models.CharField(max_length=350)),
            ],
        ),
    ]
